name: Docker CI

on:
  push:
    # enable on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose run --rm -d netcut

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install newman
      run: |
        npm install -g newman

    - name: Run POSTMAN collection
      run: |
        newman run ./test/newman-collection.json
