name: Docker CI

on:
  push:
    # enable on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker compose
      run: docker-compose run --rm netcut
