name: CI

on:
  push:
    # enable on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          tags: netcut:latest
          outputs: type=docker,dest=/tmp/netcut.tar
      -
        name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: netcut
          path: /tmp/netcut.tar
  
  test:
    runs-on: ubuntu-latest
    needs: build
    env:
      PORT: 9090
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: netcut
          path: /tmp
      -
        name: Load Docker image
        run: |
          docker load --input /tmp/netcut.tar
          docker image ls -a
      -
        name: Start Docker Container
        run: |
          docker run --rm --network host netcut --port ${{ env.PORT }}
      -
        name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: Install newman
        run: |
          npm install -g newman
      -
        name: Run POSTMAN collection
        run: |
          newman run ./test/newman_collection.json --env-var "port=${{ env.PORT }}"
