name: CI

on:
  push:
    # enable on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ubuntu:20.04
    steps:
      - name: Install Dependencies
        run: |
          apt update
          DEBIAN_FRONTEND=noninteractive apt install -y build-essential \
                                          clang \
                                          clang-format \
                                          clang-tidy \
                                          cmake \
                                          git \
                                          g++ \
                                          python
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Format
        run: |
          mkdir build
          cd build
          cmake ..
          make format
      - name: Build
        run: |
          cd build
          make
      - name: Check Coding Style
        run: |
          cd build
          make check-coding-style
          