name: Docker CI

on:
  push:
    # enable on all branches
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      PORT: 9090

    steps:
    - uses: actions/checkout@v2
    - name: Docker compose
      run: docker-compose run --rm -d netcut --port ${{ env.PORT }}

    - name: Install node
      uses: actions/setup-node@v2
      with:
        node-version: '14'
    
    - name: Install newman
      run: |
        npm install -g newman

    - name: Run POSTMAN collection
      run: |
        newman run ./test/newman_collection.json --env-var "port=${{ env.PORT }}"
